version: '2'
services:
  
    # https://github.com/bitnami/bitnami-docker-zookeeper
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper-local
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/bitnami'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
              
    # https://github.com/bitnami/bitnami-docker-kafka
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka-local
        ports:
            - '9095:9095'
        volumes:
            - 'kafka_data:/bitnami'
        environment:
            - 'ALLOW_PLAINTEXT_LISTENER=yes'
            - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
            - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT'
            - 'KAFKA_CFG_LISTENERS=INSIDE://:9095'
            - 'KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://localhost:9095'
            - 'KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE'
        depends_on:
            - zookeeper 
             
    # https://hub.docker.com/_/mongo
    mongo:
        image: 'mongo:3.4'
        container_name: mongo-local
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo
        volumes:
            - 'mongo_data:/data/db'
            - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
 
    # https://hub.docker.com/r/bitnami/redis
    redis:
        image: 'docker.io/bitnami/redis:5.0'
        container_name: redis-local
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'
    
    postgresql:
        image: 'docker.io/bitnami/postgresql:10-debian-10'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - 'postgresql_data:/bitnami/postgresql'

#    docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
    sonarqube:
        image: sonarqube:latest
        ports:
            - '9000:9000'
        environment:
            - POSTGRESQL_HOST=postgresql
            - POSTGRESQL_ROOT_USER=postgres
            - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sonarqube_db
            - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=sonarqube_user
            - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=sonarqube_pwd
            - SONARQUBE_DATABASE_NAME=sonarqube_db
            - SONARQUBE_DATABASE_USER=sonarqube_user
            - SONARQUBE_DATABASE_PASSWORD=sonarqube_pwd
            - SONARQUBE_USERNAME=admin
            - SONARQUBE_PASSWORD=admin
        volumes:
            - sonarqube_data:/bitnami

networks:
  sonarnet:

networks:
  sonarnet:
    driver: bridge
              
volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
    mongo_data:
        driver: local 
    redis_data:
        driver: local
    sonarqube_data:
        driver: local
    postgresql_data:
        driver: local
